### ISSUE TITLE
Can't flatten a contract that is inheriting from another contract located in an npm module

### ISSUE THREAD

**Issue by clemlak** [bokkypoobah/SolidityFlattener#1]
Hi there! First I wanted to say thank you for this tool 👍 

So I'm running into an issue when I try to flatten a contract that is inheriting from another contract located in an npm module.

For example, a contract called `Hello.sol` inheriting from the `Ownlable.sol` contract from the Open Zeppelin library (installed in the `node_modules` directory) will output the following error:
`Importing contracts/openzeppelin-solidity/contracts/ownership/Ownable.sol
    Processing contracts/openzeppelin-solidity/contracts/ownership/Ownable.sol
Cannot open contracts/openzeppelin-solidity/contracts/ownership/Ownable.sol for reading. Stopped at /usr/local/bin/solidityFlattener.pl line 95.`

So the explanation is simple: the script tries to find the contracts within the given directory `contracts` and not in the `node_modules` directory.

I think a _simple_ fix will be to check if the path of the imported contracts are starting with an `.` or not, so the script will know if it should grab it from the `node_modules` directory.

**Comment by bokkypoobah** [comment]
I've added a `--remapdir` switch to allow you to remap your `contracts/openzeppelin-solidity` directory to the location of your npm `node_modules/openzeppelin-solidity` subdirectory. Please test

**Comment by clemlak** [comment]
Awesome, it works perfectly! Even if the contracts within the npm module are importing other contracts!

Thanks for the fast update 👍
